language: node_js
node_js:
- "lts/*"
env:
  global:
    secure: j7Ci7eRPWCi4gN25xkntvu/j/axZlpO4IxwncjapcEKFRvgu7Yit6HvWy7/Dfw8nWDbKA+vD6CMQfjNxXpBRST66omogrj0T2lMty8PD+N3TXUKEYePnlsgAwhYJ1l7lbhcCAa5CQJ45e129xuRQFuMQT6U0AKxz9bZlM7LCaxS1ei/JjBU8eWpk/L7f5sfxIoKbNl/47R+EYMNFotF3DoqJSS0zn8sgwnw3UVcH4cDUEF6ItY4GLejgoLwjAlR+SrGVPmxirwDEOHH3po9qwEAGdTG1f2zNwK0nMelKSuoF1ZyKnN+B1Y0DCs1M+aArJGGhrrGmrQj5DvmlffNswEna7c06+YldIQyZWgKrK9gGgksPJAQ8ryDas+tp9jmrDN19+JoMwRAMz+Ngg7O4saurQwX/oTDLbzrtxGbDqGs69wUkeJ5manYS49A3QTfFt8aZO+N2JBD0wbsQXKPb9LaJniekrzYEIF4vrw7r5T7xdsiKIoyTTvWdaN71B7S+uZxH29PWbxmdywbFo3ZdKaIzGIk9YT3SNLtQqpRLWNLzF1wkvyTjBBw0egaPuf/uRW2RrmjOMB9XexCzO3kyPasz48Lf7M10lhKn/5WYH6rxBd+EytHDEHHHTJ1CIlcKinxoXj6Kn5tNWNoooJlpu7F/0bTjcYJ9drf+r0aXS0U=
